#!/bin/bash

# Detener y eliminar contenedores e imágenes anteriores si existen
docker stop samrun || true
docker rm samrun || true
docker rmi sample || true

# Crear Dockerfile
echo "FROM python:3" > Dockerfile
echo "RUN pip install Flask" >> Dockerfile
echo "WORKDIR /home/app" >> Dockerfile
echo "COPY server.py ." >> Dockerfile
echo "EXPOSE 5050" >> Dockerfile
echo "CMD python3 /home/app/server.py" >> Dockerfile

# Crear la imagen
docker build -t sample .

# Ejecutar el contenedor
docker run -d -p 5050:5050 --name samrun sample

# Verificar que el contenedor está en ejecución
docker ps -a
